### ISSUE TITLE
[jobflow]: Add more log messages at different levels like Ansible to let users know activities in progress

### ISSUE THREAD

**Issue by uthng** [uthng/jobflow#54]

**Comment by uthng** [comment]
More logs added to go routines launching job execution on remote machine but generated panic:
```
INFO:  Executing job job1

INFO:  REMOTE JOB RUN STARTED                              job=job1 hosts=host3
INFO:  REMOTE JOB RUN STARTED                              job=job1 hosts=host2
INFO:  REMOTE JOB RUN STARTED                              job=job1 hosts=host1
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 22 [running]:
sync.(*WaitGroup).Wait(0x120b7e0)
	/usr/local/go/src/sync/waitgroup.go:131 +0xbb
github.com/uthng/jobflow/vendor/github.com/uthng/golog.Log(0x3, 0xc4201355c0, 0x4, 0xc9f88d, 0x1a, 0xc420130640, 0x4, 0x4)
	/data/Projets/go/src/github.com/uthng/jobflow/vendor/github.com/uthng/golog/log.go:490 +0xec
github.com/uthng/jobflow/vendor/github.com/uthng/golog.(*Logger).Infow(0xc4201355c0, 0xc9f88d, 0x1a, 0xc420130640, 0x4, 0x4)
	/data/Projets/go/src/github.com/uthng/jobflow/vendor/github.com/uthng/golog/log.go:236 +0x6f
github.com/uthng/jobflow/job.(*Flow).execJobViaSSH(0xc4201e21e0, 0xc4201e2480, 0xc4201fc120, 0xc4201355c0)
	/data/Projets/go/src/github.com/uthng/jobflow/job/flow.go:184 +0x34f
created by github.com/uthng/jobflow/job.(*Flow).execJobRemote
	/data/Projets/go/src/github.com/uthng/jobflow/job/flow.go:139 +0x168
```
